# 
# Do not Edit! Generated by:
# spectacle version 0.15
# 
# >> macros
# << macros

Name:       omweather-weather-com-stations-db
Summary:    Stations database and source lib for weather.com for Other Maemo Weather
Version:    1.0
Release:    1
Group:      Applications/Internet
License:    GPLv2.1
URL:        https://garage.maemo.org/projects/omweather/
Source0:    %{name}-%{version}.tar.bz2
Source100:  omweather-weather-com-stations-db.yaml
BuildRequires:  pkgconfig(libxml2-dev)
BuildRequires:  pkgconfig(glib2)

%description
Stations database and source lib for weather.com for Other Maemo Weather



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
# << install post






%files
%defattr(-,root,root,-)
none
# >> files
# << files


