# 
# Do not Edit! Generated by:
# spectacle version 0.18
# 
# >> macros
# << macros

Name:       omweather-weather-com-stations-db
Summary:    Stations database and source lib for weather.com for Other Maemo Weather
Version:    1.0.1
Release:    1
Group:      Applications/Internet
License:    GPLv2.1
URL:        https://garage.maemo.org/projects/omweather/
Source0:    %{name}-%{version}.tar.bz2
Source100:  omweather-weather-com-stations-db.yaml
BuildRequires:  pkgconfig(libxml-2.0)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  gcc
BuildRequires:  make


%description
Stations database and source lib for weather.com for Other Maemo Weather



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
./autogen.sh
# << build pre

%configure --disable-static \
    --datadir="/usr/share"

make %{?jobs:-j%jobs}

# >> build post
#make
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install 

# >> install post
# << install post






%files
%defattr(-,root,root,-)
/usr/lib/omweather/weathercom
/usr/lib/omweather/libomweather-weather-com-source.so
/usr/share/omweather/copyright_icons/weather.com.png
/usr/share/omweather/db/weather.com.db
/usr/share/omweather/sources/weather.com.xml
# >> files
# << files


