/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c MeecastIf -a dbusadaptor.h:dbusadaptor.cpp com.meecast.applet.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MeecastIf
 */

MeecastIf::MeecastIf(Meecastdata *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MeecastIf::~MeecastIf()
{
    // destructor
}

void MeecastIf::SetCurrentData(const QString &station, const QString &temperature, const QString &temperature_hi, const QString &temperature_low, const QString &icon, const QString &description, uint until_valid_time, bool current, bool lockscreen, bool standbyscreen, const QString &last_update)
{
    // handle method call com.meecast.applet.SetCurrentData
    static_cast<Meecastdata *>(parent())->SetCurrentData(station, temperature, temperature_hi, temperature_low, icon, description, until_valid_time, current, lockscreen, standbyscreen, last_update);

}


