/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c OmweatherAdaptor -a omweatheradaptor.h:omweatheradaptor.cpp com.meecast.omweather.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef OMWEATHERADAPTOR_H_1312051091
#define OMWEATHERADAPTOR_H_1312051091

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.meecast.omweather
 */
class OmweatherAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.meecast.omweather")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.meecast.omweather\">\n"
"    <signal name=\"configChange\"/>\n"
"  </interface>\n"
        "")
public:
    OmweatherAdaptor(QObject *parent);
    virtual ~OmweatherAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void configChange();
};

#endif
