/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c OmweatherIntf -p omweatherintf.h:omweatherintf.cpp com.meecast.omweather.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef OMWEATHERINTF_H_1312014277
#define OMWEATHERINTF_H_1312014277

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.meecast.omweather
 */
class OmweatherIntf: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.meecast.omweather"; }

public:
    OmweatherIntf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OmweatherIntf();

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void change();
};

namespace com {
  namespace meecast {
    typedef ::OmweatherIntf omweather;
  }
}
#endif
