/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c MeecastIf -p dbusadaptor.h:dbusadaptor.cpp com.omweather.meecast.applet.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DBUSADAPTOR_H_1317059715
#define DBUSADAPTOR_H_1317059715

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.omweather.meecast.applet
 */
class MeecastIf: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.omweather.meecast.applet"; }

public:
    MeecastIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~MeecastIf();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> SetCurrentData(const QString &station, const QString &temperature, const QString &icon)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(station) << qVariantFromValue(temperature) << qVariantFromValue(icon);
        return asyncCallWithArgumentList(QLatin1String("SetCurrentData"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace omweather {
    namespace meecast {
      typedef ::MeecastIf applet;
    }
  }
}
#endif
