/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c MeecastIf -a dbusadaptor.h:dbusadaptor.cpp com.meecast.applet.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MeecastIf
 */

MeecastIf::MeecastIf(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MeecastIf::~MeecastIf()
{
    // destructor
}

void MeecastIf::SetCurrentData(const QString &station, const QString &temperature, const QString &icon)
{
    // handle method call com.meecast.applet.SetCurrentData
    QMetaObject::invokeMethod(parent(), "SetCurrentData", Q_ARG(QString, station), Q_ARG(QString, temperature), Q_ARG(QString, icon));
}

