/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c EventFeedIf -a eventfeedif.h:eventfeedif.cpp eventfeed.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "eventfeedif.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class EventFeedIf
 */

EventFeedIf::EventFeedIf(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

EventFeedIf::~EventFeedIf()
{
    // destructor
}

void EventFeedIf::refreshRequested()
{
    // handle method call com.nokia.home.EventFeed.refreshRequested
    QMetaObject::invokeMethod(parent(), "refreshRequested");
}

