/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c EventFeedIf -a eventfeedif.h:eventfeedif.cpp eventfeed.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef EVENTFEEDIF_H_1317393765
#define EVENTFEEDIF_H_1317393765

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.nokia.home.EventFeed
 */
class EventFeedIf: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.nokia.home.EventFeed")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.nokia.home.EventFeed\">\n"
"    <method name=\"refreshRequested\"/>\n"
"  </interface>\n"
        "")
public:
    EventFeedIf(QObject *parent);
    virtual ~EventFeedIf();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void refreshRequested();
Q_SIGNALS: // SIGNALS
};

#endif
