/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c WeatherDataIf -a weatherdataif.h:weatherdataif.cpp com.meecast.data.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef WEATHERDATAIF_H_1347645684
#define WEATHERDATAIF_H_1347645684

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "meegotouchplugin.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.meecast.data
 */
class WeatherDataIf: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.meecast.data")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.meecast.data\">\n"
"    <method name=\"GetCurrentWeather\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"station\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"temperature\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"temperature_hi\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"temperature_low\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"icon\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"description\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"current\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"last_update\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    WeatherDataIf(MyMWidget *parent);
    virtual ~WeatherDataIf();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString GetCurrentWeather(QString &temperature, QString &temperature_hi, QString &temperature_low, QString &icon, QString &description, bool &current, QString &last_update);
Q_SIGNALS: // SIGNALS
};

#endif
