/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c MeecastIf -a dbusadaptor.h:dbusadaptor.cpp com.meecast.applet.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbusadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MeecastIf
 */

MeecastIf::MeecastIf(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MeecastIf::~MeecastIf()
{
    // destructor
}

void MeecastIf::SetCurrentData(const QString &station, const QString &temperature, const QString &temperature_hi, const QString &temperature_low, const QString &icon, uint until_valid_time, bool current, bool lockscreen, bool standbyscreen, const QString &last_update)
{
    // handle method call com.meecast.applet.SetCurrentData
    QMetaObject::invokeMethod(parent(), "SetCurrentData", Q_ARG(QString, station), Q_ARG(QString, temperature), Q_ARG(QString, temperature_hi), Q_ARG(QString, temperature_low), Q_ARG(QString, icon), Q_ARG(uint, until_valid_time), Q_ARG(bool, current), Q_ARG(bool, lockscreen), Q_ARG(bool, standbyscreen), Q_ARG(QString, last_update));
}

