/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c EventFeedIf -p eventfeedif.h:eventfeedif.cpp eventfeed.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef EVENTFEEDIF_H_1317453816
#define EVENTFEEDIF_H_1317453816

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.nokia.home.EventFeed
 */
class EventFeedIf: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.nokia.home.EventFeed"; }

public:
    EventFeedIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~EventFeedIf();

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void refreshRequested();
};

namespace com {
  namespace nokia {
    namespace home {
      typedef ::EventFeedIf EventFeed;
    }
  }
}
#endif
