/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c WeatherDataIf -a weatherdataif.h:weatherdataif.cpp com.meecast.data.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "weatherdataif.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class WeatherDataIf
 */

WeatherDataIf::WeatherDataIf(MyMWidget *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

WeatherDataIf::~WeatherDataIf()
{
    // destructor
}

QString WeatherDataIf::GetCurrentWeather(QString &temperature, QString &temperature_hi, QString &temperature_low, QString &icon, QString &description, bool &current, QString &last_update)
{
    // handle method call com.meecast.data.GetCurrentWeather
    return static_cast<MyMWidget *>(parent())->GetCurrentWeather(temperature, temperature_hi, temperature_low, icon, description, current, last_update);
}

